### PR TITLE
Added Implicit annotations

### PR DESCRIPTION
**Pull request by eugenehuanggy**
Coffeescript indentation has to be adjusted hence huge amount of line changes.

Please feel free to point out any mistakes if any.

### CODE REVIEW

**Comment by nmccready** [comment]
This is good; sorry I forgot to include this. I intended to pipe it through this https://github.com/Kagami/gulp-ng-annotate .

**Comment by nmccready** [comment]
Closing due to this commit: ea39f79ba14a980344060647b9a638a86de07ca3

**Comment by eugenehuanggy** [comment]
Ah yes. your implementation is cleaner. :)

**Comment by eugenehuanggy** [comment]
Hi @nmccready, can i pick your brain a little?

I'm trying to use https://github.com/Leaflet/Leaflet.Editable in my project (specifically the enableEdit() and disableEdit() Mixin added to L.Polygon. In ui-leaflet, it is mentioned that i can possibly use decorators to extend the behaviour. 

I'm thinking of one approach where you can perform a $watchCollection on a list of L.PathOptions, and when editable=true, i will delete and readd the L.Path back onto the Map with .enableEdit() called. Is this a right approach? 

Another approach where i would have to keep a dictionary of all the layers added to the map, and perform .enableEdit() on the layer directly. But ui-leaflet does not seem to give direct access to L.Path.

How would you approach this problem? I would really appreciate your thoughts on this. Thanks!

**Pull request closed without merging**
